### ISSUE TITLE
3 expression  training 

### ISSUE THREAD

**Issue by cuongdothe** [amineHorseman/facial-expression-recognition-using-cnn#22]
I have try to train 3 expression, 3,4,6: Sad,Happy and Neutral.
But why i run predict a certain image, it  predicts "Angry". 
Can i change image_height  and image_width to 256 x 256 to improve the accuracy. 
image_height = 48
image_width = 48
What should i do to improve accuracy?

Thanks for your great works.

**Comment by amineHorseman** [comment]
Unfortunately, this model is not as accurate as state of art models, it's a small 5-layers model and it doesn't generalize well especially for mislabelled data (like the case in the Fer2013 dataset).

- You can try to use data augmentation, or use another dataset.
- You can try to visualize the layers to see where the model is focusing during the classification (which regions of the face are used for the decision), and try to make it focus more the on right regions (i.e: eyes, mouth)
- Try to delete to misclassified data, because it misguides the model during the training phase

Those are just few ideas

**Comment by cuongdothe** [comment]
great tip. 
thank for  your time.
